[dependencies]
  chromium = "135.0.7049.95"
  libx11 = "1.6.9"
  libxcomposite = "0.4.5"
  libxdamage = "1.1.4"
  libxi = "1.7.10"
  libxtst = "1.2.3"
  libnss3 = "3.60"
  libgdk_pixbuf2.0 = "2.42.6"
  libatk-bridge2.0 = "2.40.2"
  libgtk-3.0 = "3.24.24"
  libnspr4 = "4.30.0"
  libnss3-1d = "3.60"
  libappindicator3-1 = "12.10.0"
  xorg-server-xvfb = "1.20.4"
  libstdc++ = "10.2.1"  # Добавьте это для исправления некоторых ошибок с зависимостями
